// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Stub for VCU118 DDR4 block design wrapper (ddr_system_bd_wrapper).
// Matches the port list generated by Vivado for a block design containing
// DDR4 MIG + AXI SmartConnect (256-bit slave → 512-bit MIG master).
// Used for synthesis-only builds; replaced with real IP for bitstream.

module ddr_system_bd_wrapper (
    // DDR4 physical pins
    output              C0_DDR4_0_act_n,
    output      [16:0]  C0_DDR4_0_adr,
    output      [ 1:0]  C0_DDR4_0_ba,
    output      [ 1:0]  C0_DDR4_0_bg,
    output      [ 0:0]  C0_DDR4_0_ck_c,
    output      [ 0:0]  C0_DDR4_0_ck_t,
    output      [ 0:0]  C0_DDR4_0_cke,
    output      [ 0:0]  C0_DDR4_0_cs_n,
    inout  wire [ 7:0]  C0_DDR4_0_dm_n,
    inout  wire [63:0]  C0_DDR4_0_dq,
    inout  wire [ 7:0]  C0_DDR4_0_dqs_c,
    inout  wire [ 7:0]  C0_DDR4_0_dqs_t,
    output      [ 0:0]  C0_DDR4_0_odt,
    output              C0_DDR4_0_reset_n,

    // DDR4 reference clock
    input               C0_SYS_CLK_0_clk_n,
    input               C0_SYS_CLK_0_clk_p,

    // AXI4 slave (256-bit data, 34-bit addr, 1-bit ID)
    input       [33:0]  S00_AXI_0_araddr,
    input       [ 1:0]  S00_AXI_0_arburst,
    input       [ 3:0]  S00_AXI_0_arcache,
    input       [ 0:0]  S00_AXI_0_arid,
    input       [ 7:0]  S00_AXI_0_arlen,
    input       [ 0:0]  S00_AXI_0_arlock,
    input       [ 2:0]  S00_AXI_0_arprot,
    input       [ 3:0]  S00_AXI_0_arqos,
    output              S00_AXI_0_arready,
    input       [ 2:0]  S00_AXI_0_arsize,
    input               S00_AXI_0_arvalid,
    input       [33:0]  S00_AXI_0_awaddr,
    input       [ 1:0]  S00_AXI_0_awburst,
    input       [ 3:0]  S00_AXI_0_awcache,
    input       [ 0:0]  S00_AXI_0_awid,
    input       [ 7:0]  S00_AXI_0_awlen,
    input       [ 0:0]  S00_AXI_0_awlock,
    input       [ 2:0]  S00_AXI_0_awprot,
    input       [ 3:0]  S00_AXI_0_awqos,
    output              S00_AXI_0_awready,
    input       [ 2:0]  S00_AXI_0_awsize,
    input               S00_AXI_0_awvalid,
    output      [ 0:0]  S00_AXI_0_bid,
    input               S00_AXI_0_bready,
    output      [ 1:0]  S00_AXI_0_bresp,
    output              S00_AXI_0_bvalid,
    output    [255:0]   S00_AXI_0_rdata,
    output      [ 0:0]  S00_AXI_0_rid,
    output              S00_AXI_0_rlast,
    input               S00_AXI_0_rready,
    output      [ 1:0]  S00_AXI_0_rresp,
    output              S00_AXI_0_rvalid,
    input     [255:0]   S00_AXI_0_wdata,
    input               S00_AXI_0_wlast,
    output              S00_AXI_0_wready,
    input      [31:0]   S00_AXI_0_wstrb,
    input               S00_AXI_0_wvalid,

    // Clocks, resets, status
    output              addn_ui_clkout1_0,
    input               c0_ddr4_aresetn_0,
    output              c0_ddr4_ui_clk_0,
    output              c0_ddr4_ui_clk_sync_rst_0,
    output              c0_init_calib_complete_0,
    output    [511:0]   dbg_bus_0,
    output              dbg_clk_0,
    input               sys_rst_0
);

  // Generate a fake UI clock from the reference clock
  wire ref_clk;
  IBUFDS ibuf_ref (
      .I (C0_SYS_CLK_0_clk_p),
      .IB(C0_SYS_CLK_0_clk_n),
      .O (ref_clk)
  );

  assign c0_ddr4_ui_clk_0 = ref_clk;
  assign c0_ddr4_ui_clk_sync_rst_0 = sys_rst_0;
  assign c0_init_calib_complete_0 = ~sys_rst_0;
  assign addn_ui_clkout1_0 = ref_clk;
  assign dbg_clk_0 = 1'b0;
  assign dbg_bus_0 = 512'b0;

  // AXI slave — always ready, return zeros
  assign S00_AXI_0_awready = 1'b1;
  assign S00_AXI_0_wready = 1'b1;
  assign S00_AXI_0_bvalid = 1'b0;
  assign S00_AXI_0_bid = 1'b0;
  assign S00_AXI_0_bresp = 2'b00;
  assign S00_AXI_0_arready = 1'b1;
  assign S00_AXI_0_rvalid = 1'b0;
  assign S00_AXI_0_rid = 1'b0;
  assign S00_AXI_0_rdata = 256'b0;
  assign S00_AXI_0_rresp = 2'b00;
  assign S00_AXI_0_rlast = 1'b0;

  // DDR4 pins — tie off
  assign C0_DDR4_0_act_n = 1'b1;
  assign C0_DDR4_0_adr = 17'b0;
  assign C0_DDR4_0_ba = 2'b0;
  assign C0_DDR4_0_bg = 2'b0;
  assign C0_DDR4_0_ck_c = 1'b0;
  assign C0_DDR4_0_ck_t = 1'b1;
  assign C0_DDR4_0_cke = 1'b0;
  assign C0_DDR4_0_cs_n = 1'b1;
  assign C0_DDR4_0_odt = 1'b0;
  assign C0_DDR4_0_reset_n = 1'b0;

endmodule
